/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package montador;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kevin
 */
public class tela extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
        montador.print_simbolos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSaida = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListIntermediario = new javax.swing.JList<>();
        codigoFonteLabel = new javax.swing.JLabel();
        codigoFonteLabel1 = new javax.swing.JLabel();
        codigoFonteLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ButtonsegundaPassagem = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListSegmentos = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListSimbolos = new javax.swing.JList<>();
        codigoFonteLabel3 = new javax.swing.JLabel();
        codigoFonteLabel4 = new javax.swing.JLabel();
        ButtonPrimeiraPassagem = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jScrollPane3.setViewportView(jListSaida);

        jScrollPane4.setViewportView(jListIntermediario);

        codigoFonteLabel.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel.setText("Código Intermediario");
        codigoFonteLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        codigoFonteLabel1.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel1.setText("Código Saída");
        codigoFonteLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        codigoFonteLabel2.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel2.setText("Código Fonte");
        codigoFonteLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setText("Carregar arquivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ButtonsegundaPassagem.setText("Segunda Passagem");
        ButtonsegundaPassagem.setEnabled(false);
        ButtonsegundaPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonsegundaPassagemActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(jListSegmentos);

        jScrollPane6.setViewportView(jListSimbolos);

        codigoFonteLabel3.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel3.setText("Tabela de Segmentos");
        codigoFonteLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        codigoFonteLabel4.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel4.setText("Tabela de Símbolos");
        codigoFonteLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ButtonPrimeiraPassagem.setText("Primeira Passagem");
        ButtonPrimeiraPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPrimeiraPassagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoFonteLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonsegundaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoFonteLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoFonteLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(codigoFonteLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigoFonteLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonPrimeiraPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoFonteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoFonteLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoFonteLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoFonteLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoFonteLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPrimeiraPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonsegundaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ArquivoCarregado = new String("") ;
        String linha =new String();
        System.out.println("teste = " + System.getProperty("user.dir"));
        String CaminhoDoArquivo = new String(System.getProperty("user.dir")+"/src/main/java/montador/entrada.txt");
        BufferedReader buffRead; //reader do arquivo
        
    
        try {
            
            
            buffRead = new BufferedReader(new FileReader(CaminhoDoArquivo));
                  
            linha = buffRead.readLine();
            while (linha!=null) {                
                ArquivoCarregado=ArquivoCarregado.concat(linha+"\n");
                linha= buffRead.readLine();
            }
            jTextArea.setText(ArquivoCarregado);

            

            buffRead.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonsegundaPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonsegundaPassagemActionPerformed
        
    }//GEN-LAST:event_ButtonsegundaPassagemActionPerformed

    private void ButtonPrimeiraPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPrimeiraPassagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPrimeiraPassagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPrimeiraPassagem;
    private javax.swing.JButton ButtonsegundaPassagem;
    private javax.swing.JLabel codigoFonteLabel;
    private javax.swing.JLabel codigoFonteLabel1;
    private javax.swing.JLabel codigoFonteLabel2;
    private javax.swing.JLabel codigoFonteLabel3;
    private javax.swing.JLabel codigoFonteLabel4;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListIntermediario;
    private javax.swing.JList<String> jListSaida;
    private javax.swing.JList<String> jListSegmentos;
    private javax.swing.JList<String> jListSimbolos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
